[package]
name = "iir-test"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]

#[dependencies.peroxide]
#version = "0.30.3"
#default-features = false
#features = ["O3"]